### ISSUE TITLE
Add new option to message-warning the user if there is a data value that was updated before the defined period. (B6.4)

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization-blessed#102]
(12/12)

**Comment by idelcano** [comment]
Sorry adrian, I don't have more time to try this one.
anyway, Could do you explain the process to test it?

**Comment by adrianq** [comment]
Sorry, my bad. This is not implemented yet and I will take care of testing it in the next days. Forget about it
