### ISSUE TITLE
[User feedback]  Rule syncs but returns network error "500 Internal Server Error"

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#109]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata

I have synchronized a large rule against prod and before finishing it returns network error.

It is probably related to the server configuration.

Serverlog:
* INFO  2020-11-23 11:21:03,311 (widp.admin) Import:Start (DefaultMetadataImportService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:12,072 (widp.admin) Import:Preheat[REFERENCE] took 8.76 seconds (DefaultPreheatService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:12,225 (widp.admin) Import:Validation took 0.05 seconds (DefaultObjectBundleValidationService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:14,045 (widp.admin) Updating 505 object(s) of type Option (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:16,929 (widp.admin) Updating 53 object(s) of type OptionSet (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:20,039 (widp.admin) Updating 3 object(s) of type LegendSet (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:22,670 (widp.admin) Updating 296 object(s) of type DataElement (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:28,426 (widp.admin) Updating 5 object(s) of type DataElementGroup (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:31,114 (widp.admin) Updating 3 object(s) of type IndicatorType (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:33,792 (widp.admin) Updating 23 object(s) of type Indicator (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:36,656 (widp.admin) Updating 4 object(s) of type IndicatorGroup (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:39,335 (widp.admin) Updating 1 object(s) of type IndicatorGroupSet (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:41,985 (widp.admin) Updating 1 object(s) of type DataEntryForm (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:44,623 (widp.admin) Updating 18 object(s) of type ProgramStageSection (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:47,253 (widp.admin) Updating 1 object(s) of type ProgramStage (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:50,034 (widp.admin) Updating 1 object(s) of type Program (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:52,721 (widp.admin) Updating 1 object(s) of type EventReport (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:21:55,391 (widp.admin) Updating 1503 object(s) of type ProgramIndicator (DefaultObjectBundleService.java [catalina-exec-9])

At this point the api has returned the 500 error.

<pre>* INFO  2020-11-23 11:21:55,442 Login attempt: ignacio.foche (TwoFactorAuthenticationProvider.java [catalina-exec-10])
* WARN  2020-11-23 11:21:55,529 Authentication event AuthenticationSuccessEvent: ignacio.foche; details: org.hisp.dhis.security.spring2fa.TwoFactorWebAuthenticationDetails@1c07a: RemoteIpAddress: 10.28.26.74; SessionId: F9798CF201CCC514D9B3B02A899EB609 (LoggerListener.java [catalina-exec-10])
* WARN  2020-11-23 11:21:55,530 Authentication event SessionFixationProtectionEvent: ignacio.foche; details: org.hisp.dhis.security.spring2fa.TwoFactorWebAuthenticationDetails@1c07a: RemoteIpAddress: 10.28.26.74; SessionId: F9798CF201CCC514D9B3B02A899EB609 (LoggerListener.java [catalina-exec-10])
* WARN  2020-11-23 11:21:55,530 Authentication event InteractiveAuthenticationSuccessEvent: ignacio.foche; details: org.hisp.dhis.security.spring2fa.TwoFactorWebAuthenticationDetails@1c07a: RemoteIpAddress: 10.28.26.74; SessionId: F9798CF201CCC514D9B3B02A899EB609 (LoggerListener.java [catalina-exec-10])
* INFO  2020-11-23 11:22:00,070 Login attempt: widp.admin (TwoFactorAuthenticationProvider.java [catalina-exec-5])
* WARN  2020-11-23 11:22:00,156 Authentication event AuthenticationSuccessEvent: widp.admin; details: org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 10.28.26.74; SessionId: null (LoggerListener.java [catalina-exec-5])
* INFO  2020-11-23 11:22:13,989 (widp.admin) Updating 106 object(s) of type ProgramRuleVariable (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:22:16,959 (widp.admin) Updating 5 object(s) of type ProgramIndicatorGroup (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:22:19,959 (widp.admin) Updating 55 object(s) of type Chart (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:22:24,254 (widp.admin) Updating 14 object(s) of type ReportTable (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:22:27,730 (widp.admin) Updating 2 object(s) of type Dashboard (DefaultObjectBundleService.java [catalina-exec-9])
* INFO  2020-11-23 11:22:28,899 Cleared Hibernate caches (DefaultHibernateCacheManager.java [catalina-exec-9])
* INFO  2020-11-23 11:22:28,901 (widp.admin) Import:Commit took 76.67 seconds (DefaultMetadataImportService.java [catalina-exec-9])
* INFO  2020-11-23 11:22:28,901 (widp.admin) Import:Done took 85.59 seconds (DefaultMetadataImportService.java [catalina-exec-9])
</pre>
looking in the backend log the migration was successful.

Ina.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1606127270390942088.png )

**Comment by adrianq** [comment]
@idelcano This a known issue. Basically, the WHO frontend returns a timeout error after a certain amount of time (60secs?).  The import call keeps going on in the background but the app has already received the timeout. We have a solution for this: to implement async jobs in the app. This implementation will be done either for the next release or for the following one. I am closing this issue as it is not a real bug but feel free to open it again if you consider the problem has to do with something else.
