### ISSUE TITLE
[User feedback] List of charts not loading

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#113]
## dhis2

Username: rose.mabelle

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata/edit/B3DUE2uK2Af

I'm unable to use metadata sync to migrate charts to other instances because the list of charts is not loading.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1608255203878873132.png )

**Comment by SferaDev** [comment]
2.34: Added visualizations enpoint, deprecates charts and reportTables APIs

**Comment by adrianq** [comment]
Will be fixed in 2.8.0
