### ISSUE TITLE
[User feedback] Empty list in reporTables or charts in 2.34.3

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#114]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata/new

The list of charts and reportTables are empty.
I don't see errors in network calls.
Possibly the way to collect them from the api has changed, and maybe they are visualizations now.

Error in the console:
index.html#/sync-rules/metadata/new:1 Uncaught (in promise) Error: 500
    at new t (6.cbdf46dd.chunk.js:2)
    at 6.cbdf46dd.chunk.js:2
    at t.<anonymous> (6.cbdf46dd.chunk.js:2)
    at 6.cbdf46dd.chunk.js:2
    at Object.next (6.cbdf46dd.chunk.js:2)
    at s (6.cbdf46dd.chunk.js:2)

Ina

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1608280050599267172.png )

**Comment by adrianq** [comment]
Will be fixed in 2.8.0

**Comment by idelcano** [comment]
I have tried it and it is fixed
