### ISSUE TITLE
[User feedback] Error upgrading to last version in 2.30-datasync-sender

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#118]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8081/api/apps/MetaData-Synchronization/index.html

Tested with lucia user and all roles.
i been able to install the last metadatsync version removing the datastore and the app, and installing it from 0

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1609152094345269559.png )

**Comment by idelcano** [comment]
I have reported this issue, it seems of low priority, possibly it only affects this docker.

**Comment by adrianq** [comment]
Closing this issue as we have not been able to reproduce it in a while
