### ISSUE TITLE
[User feedback] Option sets  and program Sections missing from Tracker Package

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#120]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/ModulePackage-Generation/index.html#/packages

Hello guys, Here Lucia (GMP).
I have created a new package of the tracker program "ENTO- MOSQUITO TRACKER"  and tried to import it into a empty instance (all in 2.34). It seems that some dependencies are not exported with the package, namely the Option Sets and some program sections: 
1) 	"Invalid reference [MHwU8yVTvfz] (ProgramSection) on object ENTO- Mosquito collection [Mk9ocCvATwK] (Program) for association `programSections". and
2) 	Invalid reference [cxgdcCsurku] (ProgramSection) on object ENTO- Mosquito [Oj5hUu2m0gP] (Program) for association `programSections`

Could you have a look? Thanks 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1611128378986807654.png )

**Comment by adrianq** [comment]
It seems to be fixed in v2.14.0
