### ISSUE TITLE
[User feedback] reportTables : no result found

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#123]
## dhis2

Username: ramon.pomareta

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/MetaData-Synchronization/index.html#/sync/metadata

It does not list the reportTables, however the API call seems OK, it finds the result. The count is also OK, see 8 in the picture.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1611754350823895985.png )

**Comment by adrianq** [comment]
Will be fixed in 2.8.0

**Comment by idelcano** [comment]
I have tried it and it is fixed
