### ISSUE TITLE
[User feedback] Synchronizing one orgUnitGroup gives network error

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#125]
## dhis2

Username: ramon.pomareta

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync/metadata

I cannot select the dependencies aswell

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1612344064609806150.png )

**Comment by idelcano** [comment]
I will ask to ramon for more detailed explanation.

**Comment by adrianq** [comment]
This doesn't seem to be an error anymore
