### ISSUE TITLE
[User feedback] Department?

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#126]
## dhis2

Username: bao-admin

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://dhuser.baosystems.com/api/apps/MetaData-Synchronization/index.html#/modules/new

Hi, I'm trying out the app. Looks packed with features.
I'm not clear what Department refers to. Looking at the code I think it's a UserGroup but it still cannot find any userGroup to link to. I think also the docs don't tell much.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-161340478697633189.png )

**Comment by davidhuser** [comment]
hello :-)

**Comment by ifoche** [comment]
Hi @davidhuser ! I hope everything's fine on your end.

Answering your question. That's exactly a user group as you guesed. The idea is that you link a module to a user group that represent your department (or whatever other distribution you may have in your organization). Later, when you connect that to a github repository, each department represent a branch so every "department" have their metadata fully separated, and can provide write per-branch write permissions. 

Does that clarify a bit?

Best

**Comment by davidhuser** [comment]
Hi @ifoche - thanks yes it does! I'm not sure what a Module and a Package represents though as I did not find any documentation around it. Is a module a multi-class metadata object consisting of individual packages?

**Comment by ifoche** [comment]
A module would be kind of a pointer to any group of metadata objects inside an instance. A package is a json file representing that metadata. So somehow a module is something dynamic, because it points to live metadata, while a package is a static representation of a module in a certain moment. That's why packages contains versioning.
