### ISSUE TITLE
[User feedback] After unselecting an item from the mapping the "only selected" gets stack

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#127]
## dhis2

Username: admin

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/instances/mapping/DxeqLCtLIxZ/tracker

And it doe snot show all the available metadata objects again.
(Lucia)

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1615505051433926492.png )

**Comment by adrianq** [comment]
Fixed in v2.14.0
