### ISSUE TITLE
[User feedback] Tracker metadata packages missing ProgramSections

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#130]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/packages

Hi guys, I tested the import of the packages generated from a module containing two different tracker programs of DISCOVERY, i.e. ENTO-MOSQUITO and ENTO-MOSQUITO COLLECTION, and it seems like the only missing metadata in the package (in order to be able to install it into a blank instance) are the ProgramSections. Could you include them in the generation of the packages? Thanks!

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1616712934920339323.png )

**Comment by adrianq** [comment]
It seems to be fixed in 2.14.0
