### ISSUE TITLE
[User feedback] All instances say "with logged user" on manual sync

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#131]
## dhis2

Username: ignacio.foche

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.146 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync/metadata

Looks like there's an error in this component, as it's reading "with logged user" for all instances. However, if I'm not wrong only "This instance" should be saying that

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1617063738952160659.png )

**Comment by SferaDev** [comment]
Bug introduced in 2.8.0 with security feature by moving username and password to another dataStore key. Fixed on 2.9.0.
