### ISSUE TITLE
[User feedback] Error

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#134]
## dhis2

Username: admin

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
- Platform: Win32

## User report
URL: https://ennrims.naca.gov.ng/api/apps/MetaData-Synchronization/index.html#/instances/edit/F7yUdieLQ70

Network error, check if server is up and CORS is enabled

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1617718601400255810.png )

**Comment by adrianq** [comment]
Not enough information. Cannot reproduce
