### ISSUE TITLE
[User feedback] Error synchronizing dashboards 

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#138]
## dhis2

Username: ramon.pomareta

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36
- Platform: Win32

## User report
URL: https://portal-uat.who.int/dhis2/api/apps/MetaData-Synchronization/index.html#/sync/metadata

Hi, I am not able to sync dashboards. 

When I download the payload and upload manually through the Import/export the server logs gives an

Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uk_1dw8gju4leg7iud4gpsr5r1ng"
  Detail: Key (uid)=(fe0LTXr1NSp) already exists.

When opening the json I am actually seeing all mapViews duplicated, once inside the map, once in a mapViews key.

The dashboard I am trying to sync is called:
VL Geo

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1622126100673862978.png )

**Comment by adrianq** [comment]
This issue seems to be fixed in version 2.14.0
