### ISSUE TITLE
[User feedback] Interoperability- Mapping options shows errors

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#140]
## dhis2

Username: admin

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/instances/mapping/cOgqqpRqjte/global

Hello guys,
In advance of the workshop, I am starting to map the metadata of some of the interoperability cases by myself. 
I see some errors after the manual mapping of one options against another one.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1627996706439569733.png )

**Comment by adrianq** [comment]
Fixed in 2.14.0
