### ISSUE TITLE
[User feedback] Can't select items on second page

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#141]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata/new

Hi guys, Lucia here.
I observed that when you want to select objects in the second page, after selecting one, MD Sync sends you back to the first page. 
Could you fix it in a future release?
Thanks!

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1628497531972925289.png )

**Comment by adrianq** [comment]
Already fixed 2.14.0
