### ISSUE TITLE
[User feedback] Ignore data with same value does not apply mapping

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#142]
## dhis2

Username: arico

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8082/#/sync-rules/aggregated/edit/AuDdHly6prD

If the ignore data with same value on destination is checked but the org units do not match (requires mapping), fails with 409 and sync process stalls.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1628584639643976068.png )

**Comment by SferaDev** [comment]
Reported by @SferaDev 

```ts
        const existingPayload = dataParams.ignoreDuplicateExistingValues
            ? await this.mapPayload(instance, await this.buildPayload(instance))
            : { dataValues: [] };
```
