### ISSUE TITLE
[User feedback] problem importing program

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#144]
## dhis2

Username: ramon.pomareta

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync/metadata

Hi!

two issues:
1. in the screen: PRs do not exist in the destination instance, it raises this error. It does not happen when exporting/importing through the standard import. (not reproducible since I am going to import it through the standard one in few minutes)

2. It happened also when PR exist, if you try this week, you can test against PREPROD.

The program is:
vFcxda6dJyT

Thanks!

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1630423598553543893.png )

**Comment by SferaDev** [comment]
@idelcano Please review if it's solved with 2.11
