### ISSUE TITLE
[User feedback] programRuleActions missing

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#146]
## dhis2

Username: ramon.pomareta

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/MetaData-Synchronization/index.html#/sync/metadata

It seems the program Rule actions are not included in the payload. Thanks for helping!

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1630664857770377119.png )

**Comment by SferaDev** [comment]
This is fixed in latest version
