### ISSUE TITLE
[User feedback] Error While Testing Connection

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#149]
## dhis2

Username: projmanager

## Browser
- Name: Mozilla
- Version: 5.0 (Windows)
- Platform: Win32

## User report
URL: http://nmdrnigeria.ng/api/apps/MetaData-Synchronization/index.html#/instances/new

Network error, check if server is up and CORS is enabled

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-163617906461712249.png )

**Comment by adrianq** [comment]
Not enough information to reproduce the error
