### ISSUE TITLE
[User feedback] Error Message

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#150]
## dhis2

Username: projmanager

## Browser
- Name: Mozilla
- Version: 5.0 (Windows)
- Platform: Win32

## User report
URL: http://nmdrnigeria.ng/api/apps/MetaData-Synchronization/index.html#/sync/aggregated

Network error when attempting to fetch resource

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1636179171226195694.png )

**Comment by adrianq** [comment]
We cannot reproduce the error.
