### ISSUE TITLE
[User feedback] Sharings settings per instance

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#20]
## dhis2

Username: widp.admin

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/Metadata-Synchronization/index.html#/instance-configurator

During the training today, a request for the next versions that makes sense, has been to define sharing settings per instance. That way, we could define a Sync Rule with all instances, but depending on the user executing the sync rule, only some of them can be applied. 

This has an impact also in the GUI, as there should be a new way to override the instances selection of the sync rule

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1571304124807531873.png )

**Comment by adrianq** [comment]
Implemented in 2.8.0
