### ISSUE TITLE
[User feedback] Paging cannot be clicked

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#26]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/Metadata-Synchronization/index.html#/sync-rules/metadata/new

I guess it's due to the filters overlapping issue that paging goes out from the screen and cannot be clicked

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1577781073300862436.png )

**Comment by adrianq** [comment]
Fixed in 0.6.0
