### ISSUE TITLE
[User feedback] In relative periods selection there are no "This" periods

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#28]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/Metadata-Synchronization/index.html#/sync/aggregated

Sorry for the screenshot because I couldn't make the feedback work with the agg data sync rule creation dialog. 

There seems to be only the "Last" relative periods, but not the "This" relative periods from DHIS2. 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1577781725808609232.png )

**Comment by adrianq** [comment]
We should include at least the following options:
- This day
- This week
- This month
- This year
