### ISSUE TITLE
[User feedback] Agg data sync rule not working with last year on 31 dec

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#29]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/Metadata-Synchronization/index.html#/sync-rules/aggregated/edit/YYnr60vBd8n

If I select "Last year" the json file that's imported is empty, and likewise if I download the json. But if I select a fix date from dec 2017 to dec 2019 then the data is sent and downloaded. I suspect it has to do with today being 31st Dec

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-157780630434789470.png )

**Comment by ifoche** [comment]
![Screenshot from 2019-12-31 16-25-21](https://user-images.githubusercontent.com/10931645/71626028-50bb9100-2beb-11ea-9af3-14c4616329b9.png)

**Comment by SferaDev** [comment]
@ifoche Couldn't reproduce it, created two data values on ADMIN check with today's date (december 31). Tried to sync with "last year" period and it did synchronize the newly created data values.

Also the API call has ``startDate=2018-12-31&endDate=2019-12-31`` which is correct.

**Comment by adrianq** [comment]
@SferaDev I also had a look at this issue together with @ifoche Actually, those dates are not correct. You executed it yesterday and you chose 'Last Year' there the dates should be startDate=2017-12-31&endDate=2018-12-31 and if the user chooses 'This Year' (we need to add this option) then we should use the dates you mentioned, right?

**Comment by SferaDev** [comment]
> @SferaDev I also had a look at this issue together with @ifoche Actually, those dates are not correct. You executed it yesterday and you chose 'Last Year' there the dates should be startDate=2017-12-31&endDate=2018-12-31 and if the user chooses 'This Year' (we need to add this option) then we should use the dates you mentioned, right?

Ah, semantics issue here! :)

I always thought of it as ``one year before today`` not ``one year before current``. IFF we follow this pattern, all the options should be adapted?

**Comment by adrianq** [comment]
What is the current behaviour for pivot tables in DHIS2? IMHO, that is the rule we should follow. Btw, this is related with this other issue https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/28

**Comment by SferaDev** [comment]
> What is the current behaviour for pivot tables in DHIS2? IMHO, that is the rule we should follow. Btw, this is related with this other issue #28

Pivot tables:

![image](https://user-images.githubusercontent.com/2181866/71640835-42748000-2c92-11ea-896b-969a3bcfe595.png)

**Comment by adrianq** [comment]
I meant in terms of how pivot table understand 'Last' vs 'This'. I think pivot table understands those two concepts as Nacho does. Let's talk now anyway...
