### ISSUE TITLE
[User feedback] the password is visible

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#40]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/instances/edit/hF2x23C2ikK

I can see the password of any configurated instance (by another user) in the source code using the inspector, in the value attribute of the input element.

(Ina)

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1581510306121654537.png )

**Comment by adrianq** [comment]
@idelcano this should be solved in branch development-malaria. I am closing this issue now but give it a try on Thursday and confirm it is actually solved for you as well.
