### ISSUE TITLE
[User feedback] cannot send feedback when a modal is on the screen

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#42]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/instances/mapping/Y5QsHDoD4I0/aggregated

I tried to send a feedback comment with a modal on the screen and it looks like the modal takes the keyboard control so it's not possible to write on the feedback modal. 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1583138132024845837.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/metadata-synchronization/pull/402/commits/a139f0379b9fd9de0831429968e69544574a3d35
