### ISSUE TITLE
[User feedback] Auto-mapping ends up with a not visible selection

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#43]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/instances/mapping/Y5QsHDoD4I0/aggregated

It's a minor problem, but when you auto-map, you want to see the result of the mapping, and what you get is a selection that you cannot see because the listing is not showing you the selected data element, and is saying (in other pages) so actually you need to look for it or filter by selected. Wouldn't it be better to automatically switch on the filter and show the selected one after an automapping?

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1583138237781455924.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/metadata-synchronization/pull/391/commits/b69f0110e8a4b59597f5150300c0fe59e9913553
