### ISSUE TITLE
[User feedback] Layout problems

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#44]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/instances/mapping/p9rDbSRjHjA/tracker

Looks like the side card is now leaving outside the box most of the text elements that are inside, not only the API link

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1583140513475198158.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/d2-ui-components/pull/135
