### ISSUE TITLE
[User feedback] Search field doesn't properly work

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#45]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/instances/mapping/p9rDbSRjHjA/tracker

Being in events sync, I try to look for a DE called ENTO-Adult-Household Head name and it doesn't show anything

First I thought that search might not be working for children, and just for parents, but actually the program's called ENTO-Adult so the search "ENTO-Adult" should be showing something

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1583143063874608049.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/metadata-synchronization/pull/391/commits/cff25b43451671fdeafd76dab6ebbd20f2f69a83
