### ISSUE TITLE
[User feedback] Highlight and expand children orgunit Tree

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#50]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/instances/mapping/kiNVCEtS8Cl/orgUnit

When a user clicks "select with children", please highlight children in orange and expand the children orgUnit tree.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1583238009400752055.png )

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/metadata-synchronization/pull/407/commits/914d90788ab3ee006fbb3d3d786c7d8345719b29
