### ISSUE TITLE
[User feedback] Nothing appears on menu for selected items

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#51]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/sync-rules/events/edit/j7XWbZX08l5

If the element is selected, then the menu doesn't appear

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1584393430517795776.png )

**Comment by idelcano** [comment]
I see the dot menu always, but the details info dissapear when you have selected a program:

![screenshot-localhost_8080-2021 03 05-13_15_33](https://user-images.githubusercontent.com/5302538/110114472-04527f00-7db5-11eb-905a-20ebdc82dc2c.png)
![screenshot-localhost_8080-2021 03 05-13_15_47](https://user-images.githubusercontent.com/5302538/110114481-06b4d900-7db5-11eb-831a-8e23724b482a.png)

**Comment by adrianq** [comment]
As discussed this is not an error because "Details" is an individual action. When multiple rows are selected the 3-dots shows only bulk action
