### ISSUE TITLE
[User feedback] related-metadata mapping disappeared

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#52]
## dhis2

Username: who

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/instances/mapping/kiNVCEtS8Cl/aggregated

I cannot see the related metadata mapping anymore

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1584394801969777496.png )

**Comment by ifoche** [comment]
looks like I've been really unlucky and selected several times DEs and programs without any related metadata mapping...so let me close this issue. Sorry for it
