### ISSUE TITLE
[User feedback] Selection is not proposing select all in organisation unit mapping

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#56]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/instances/mapping/jByWTxgTnWl/orgUnit

In dataelements mapping when you select all the elements in a page, it proposed you to select all the elements that matches the filter (all pages)

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1586864353962500100.png )

**Comment by idelcano** [comment]
This is not a bug, it is a suggestion:
Now you can select all the elements of the visible page, and I propose to be able to select all the elements found in the search.

The issue could be closed.
