### ISSUE TITLE
[User feedback] Dashboard meta-data sync - MapView missing

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#58]
## dhis2

Username: ryan

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
- Platform: MacIntel

## User report
URL: http://localhost:8081/dhis/api/apps/MetaData-Synchronization/index.html#/sync/metadata

Selecting a dashboard for a meta-data sync. Results in a  missing map MapView.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1588846945357753986.png )

**Comment by SferaDev** [comment]
Steps to reproduce:

1. Create a dashboard with a map inside
2. Sync the dashboard and see it fails

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/metadata-synchronization/pull/524
