### ISSUE TITLE
[User feedback] Dashboard meta-data sync - LegendSet missing

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#59]
## dhis2

Username: ryan

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
- Platform: MacIntel

## User report
URL: http://localhost:8081/dhis/api/apps/MetaData-Synchronization/index.html#/sync/metadata

A dashboard meta-data sync results in a missing LegendSet. Seems and Orgunit is missing as well. In other dashboard attempts, the LegendSet is systematically missing.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1588847275158464300.png )

**Comment by SferaDev** [comment]
Steps to reproduce:

1. Create a LegendSet
2. Create a Pivot Table and assign it the legendSet
3. Create a dashboard with the Pivot table
4. Synchronize

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/metadata-synchronization/pull/524
