### ISSUE TITLE
[User feedback] DE of type file resources not supported

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#61]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/history/aggregated

The resource associated with the resource's uid does not exist on the destination server, and causes a nullpointerexception.
for example, in the migration from malaria to widp:
dataelement: c9p5aky1SCy
dataset: PWCUb3Se1Ie

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1590485709330755953.png )

**Comment by idelcano** [comment]
Still failing, I think this issue does not make sense if we are not going to add the feature to send files for the dataelements of type resource_file

**Comment by adrianq** [comment]
Fixed in 2.15.0
