### ISSUE TITLE
[User feedback] mapviews are not included in Dashboard

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#65]
## dhis2

Username: ramon.pomareta

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet-uat.who.int/dhis2/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata/edit/yRWre5hc3UV

I think the screenshot is not showing the right pane of the Dashboard dependencies.

In any case, dashboards do not include mapviews. So Dashboards cannot be created if they include maps.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1593520309228829722.png )

**Comment by SferaDev** [comment]
Already fixed in https://github.com/EyeSeeTea/metadata-synchronization/pull/524/files

**Comment by adrianq** [comment]
Fixed in https://github.com/EyeSeeTea/metadata-synchronization/pull/524
