### ISSUE TITLE
[User feedback] When selecting "Only selected item" filter there's an error

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#66]
## dhis2

Username: ignacio.foche

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata/edit/I2sYLRsJfS3

This is happening in WHO DEV

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1594748053579668733.png )

**Comment by SferaDev** [comment]
Can reproduce, typical error HTTP 414 error with request too large, being here 2269 elements selected.

**Comment by adrianq** [comment]
Fixed in 2.0.0
