### ISSUE TITLE
[User feedback] Relabel options in MD Sync

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#67]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync/metadata

I think this is about dependencies right?
If so, could we relabel "Include Exclude selection" for "Select dependencies" and "Use default configuration" for "Use default dependencies"

Thanks!
Lucia

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596011297897110528.png )

**Comment by adrianq** [comment]
Fixed in release 2.0.0
