### ISSUE TITLE
[User feedback] Aggregated data aggreation

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#69]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync/aggregated

Hi guys,
I think we need to enable two different aggreations here:
1) a user may want to aggregate data collected in one health facility at daily frequency into annual data.
2) a user may want to aggregate data collected from   health facilities present in a district, at district and annual level.
These two types of aggregation should be possible. To me it looks like now only 2 is possible. 
In addition, please add the red message to the Event Aggregation window.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-159601909329230719.png )

**Comment by adrianq** [comment]
Fixed in 2.0.0
