### ISSUE TITLE
[User feedback] image not loading

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#70]
## dhis2

Username: ignacio.foche

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://dev2.eyeseetea.com:8085/api/apps/MetaData-Synchronization/index.html#/modules/config

on module store connection

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1598006822592133670.png )

**Comment by adrianq** [comment]
Fixed in 2.1.0
