### ISSUE TITLE
[User feedback] mapviews error

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#71]
## dhis2

Username: ramon.pomareta

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata

It says invalid references for a mapview. It uploads ok using standard import-export

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1598340653541446040.png )

**Comment by adrianq** [comment]
Fixed in 2.0.0.
