### ISSUE TITLE
[User feedback] Borro instancias y aparece este mensaje

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#72]
## dhis2

Username: ignacio.foche

## Browser
- Name: Mozilla
- Version: 5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
- Platform: MacIntel

## User report
URL: http://dev2.eyeseetea.com:8085/api/apps/MetaData-Synchronization/index.html#/instances

Tras seleccionar y borrar varias instancias aparece este mensaje como si aun estuvieran seleccionadas. 
También me pasó algo parecido asi: empiezas una sincronización de eventos. Seleccionas manualmente 4 eventos en el paso 3. Terminas el proeso ( en este caso da error). Vuelves a empezar una sincronización de otros eventos diferentes.El formulario multistep en el paso 3 indica que hay selccionados objetos en otras páginas porque ha guardado la selección que ya había ( en este caso no tiene sentido que lo haga porque son otros objetos diferentes)

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1598885525605164974.png )

**Comment by adrianq** [comment]
This will be fixed in version 2.1.0
