### ISSUE TITLE
[User feedback] validation of URL fails if name of instance is locahost

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#73]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/instances/edit/TNzxxhDNOXV

For some reason, we cannot use localhost as the name of an instance, because then the validation of URL fails

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1599142312532597982.png )

**Comment by adrianq** [comment]
Fixed in 2.1.0
