### ISSUE TITLE
[User feedback] OrgUnit group filter not working

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#75]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/MetaData-Synchronization/index.html#/instances/mapping/b4HD5svS12V/orgUnit

Please check

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1600365403226980506.png )

**Comment by adrianq** [comment]
Fixed in 2.2.0
