### ISSUE TITLE
[User feedback] Network error but import was ok

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#76]
## dhis2

Username: ramon.pomareta

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata

It took 64s in the log.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1600697853095917611.png )

**Comment by adrianq** [comment]
This has to do with a timeout error on the NGINX/Apache. The call is properly executed in the backend but the frontend infrastructure raised up a timeout. Not much to do here as this is not a frequent error and the user is already informed of it
