### ISSUE TITLE
[User feedback] Empty exclude rule on optionsets

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#77]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata/edit/QpCLQ6U68TO

With the default configuration when synchronizing an optionset and its options, the optionset does not have its options referenced.
Although the options do have their optionsets referenced, the result is that the options are not visible from the optionset.

I have tried to move all the dependencies to include, and now if the optionsets has its options references, but I see that there is an empty exclude rule.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1601290320261720082.png )

**Comment by SferaDev** [comment]
Related https://jira.dhis2.org/browse/DHIS2-2731
