### ISSUE TITLE
[User feedback] No destination instance when executing a pull

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#78]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/sync/metadata

In a manual sync the instance selector step is mandatory and there's no destination instance like "This instance"

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1601371383307302873.png )

**Comment by SferaDev** [comment]
Related to https://github.com/EyeSeeTea/metadata-synchronization/pull/608

Should be like in SyncRulesPage

![pic](https://user-images.githubusercontent.com/2181866/91545893-f7defc80-e921-11ea-9e70-9c33ea714e3d.png)

**Comment by adrianq** [comment]
Fixed in 2.3.0
