### ISSUE TITLE
[User feedback] Dataset references to OU blocking the pull

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#79]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Linux x86_64

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata

There's no way to bring a dataset from another instance because the references to OUs block the sync to happen

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1601371635604515586.png )

**Comment by adrianq** [comment]
Fixed in 2.3.0
