### ISSUE TITLE
[User feedback] Error synchronizing orgunit groups

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#80]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/history/metadata

The error is due to an invalid configuration in the org units feature type. For example, Ethiopia in 2.30 has the feature type MULTIPOLIGON, but in 2.34, after migration, the feature type is Polygon. 
When I try to execute this rule, the backend shows an error: invalid geometry type.
2.30 https://extranet.who.int/dhis2-dev/api/organisationUnits/SnYHrnchKjL
2.34 https://extranet.who.int/dhis2-cont-dev/api/organisationUnits/SnYHrnchKjL

I'm not sure if we should identify the correct feature type in the metadata sync mapping, or if it should be considered a misconfigured metadata bug to resolve in 2.30 updating the org units.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1601452042212563654.png )

**Comment by idelcano** [comment]
I think the problem was really in the multypoligon name of the featuretype.
I have tried some rules and it seems resolved in the latest version. It could be closed.
