### ISSUE TITLE
[User feedback] Automatically logs in to Automated Bot Account after syncing data from DEV to DEV-CONT

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#82]
## dhis2

Username: widp.admin

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-cont-dev/api/apps/MetaData-Synchronization/index.html#/

Logged in to both DEV and DEV-CONT using my account (rose.mabelle) then I synced metadata using the MDSync from DEV to DEV-CONT.

Refreshed DEV-CONT to check if the metadata were synced then after the page refresh I was suddenly a superuser and also able to view data of other units (HEP C) when checked I saw that I was logged in using the Bot-Automated Tasks account. 

Happens every time I would synced data from DEV to DEV-CONT. I get logged in to the Bot-Automated Tasks account in DEV-CONT.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1601538684849426508.png )

**Comment by adrianq** [comment]
Fixed in 2.3.0
