### ISSUE TITLE
[User feedback] Sync map rule failed against 2.34 [Dashboards]

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#83]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/history/metadata

Rule in dev: NTD - 05102020 - Dashboard leprosy
Catalina.out log:

 * INFO  2020-10-05T10:12:04,074 (widp.admin) Import:Start (DefaultMetadataImportService.java [catalina-exec-3])
 * INFO  2020-10-05T10:12:04,251 (widp.admin) Import:Preheat[REFERENCE] took 0.17 seconds (DefaultPreheatService.java [catalina-exec-3])
 * INFO  2020-10-05T10:12:04,267 (widp.admin) Import:Validation took 0.00 seconds (DefaultObjectBundleValidationService.java [catalina-exec-3])
 * INFO  2020-10-05T10:12:04,268 (widp.admin) Creating 6 object(s) of type EventChart (DefaultObjectBundleService.java [catalina-exec-3])
 * INFO  2020-10-05T10:12:04,356 (widp.admin) Creating 1 object(s) of type MapView (DefaultObjectBundleService.java [catalina-exec-3])
 * INFO  2020-10-05T10:12:04,385 (widp.admin) Creating 7 object(s) of type Visualization (DefaultObjectBundleService.java [catalina-exec-3])
 * INFO  2020-10-05T10:12:04,460 (widp.admin) Creating 1 object(s) of type Map (DefaultObjectBundleService.java [catalina-exec-3])
 * WARN  2020-10-05T10:12:04,482 SQL Error: 0, SQLState: 23505 (SqlExceptionHelper.java [catalina-exec-3])
 * ERROR 2020-10-05T10:12:04,482 ERROR: duplicate key value violates unique constraint "uk_1dw8gju4leg7iud4gpsr5r1ng"
  Detail: Key (uid)=(AxfWGKUoBEO) already exists. (SqlExceptionHelper.java [catalina-exec-3])

Map:
https://extranet.who.int/dhis2-cont-dev/api/identifiableObjects/biycmS3uC87
Mapview:
https://extranet.who.int/dhis2-cont-dev/api/identifiableObjects/AxfWGKUoBEO

I can't find those uids in the chart, map, or mapview tables on database.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1601886659376743083.png )

**Comment by idelcano** [comment]
This dashboard has 2 errors.
Metadatasync create the json to be synced (or downloaded) with some dashboarditems as null. 
This error will be fixed in metadatasync
And other error trying to sync from preprod to dev in the WHO instances, maybe its some related with the permissions, when you try to import the dashboard fixed, you will get a duplicate constraint error in catalina.out log.
I will talk with nacho to fix the second error during gm.

**Comment by adrianq** [comment]
Fixed on 2.8.0
