### ISSUE TITLE
[User feedback] Could not find a way to exclude orgUnits from the dependencie

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#84]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/modules/edit/qa4lbJy2NZF

In order to generate metadata packages, we need to exclude the orgUnits from the metdata. However I do not seem to find the way to do it..
Lucia

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1602254895370898331.png )

**Comment by idelcano** [comment]
Duplicate issue: 
https://github.com/EyeSeeTea/metadata-synchronization-blessed/issues/81
not solved yet

**Comment by adrianq** [comment]
Closing and keeping #81 then
