### ISSUE TITLE
[User feedback] Bug downloading metadata package

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#86]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/modules

Failed to load resource: the server responded with a status of 404 ()
8.925ef8e9.chunk.js:1 Uncaught (in promise) TypeError: Cannot read property 'excludeRules' of undefined
    at 8.925ef8e9.chunk.js:1
    at 8.925ef8e9.chunk.js:1

Lucia

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1602271833279710351.png )

**Comment by adrianq** [comment]
This cannot be reproduce anymore
