### ISSUE TITLE
[User feedback]  creation date in the summary

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#87]
## dhis2

Username: idelcano

## Browser
- Name: Mozilla
- Version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
- Platform: Linux x86_64

## User report
URL: https://extranet.who.int/dhis2-dev/api/apps/MetaData-Synchronization/index.html#/sync-rules/metadata

It would be useful for the admin team to be able to sort the rules by creation date.
Ina

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1602578087982881660.png )

**Comment by idelcano** [comment]
Its done, we can close this issue
