### ISSUE TITLE
[User feedback] Some options sets not included in package

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#89]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2-ento-vc/api/apps/MetaData-Synchronization/index.html#/modules/edit/NHk6vwzHfz9

Hi Guys,
I am preparing a package with these two tracker programs from instance: https://extranet.who.int/dhis2-ento-vc
I am using default dependencies.

I am seeing that there are two things that are not properly included in the package: programSections and optionSets of some data elements. Please see the error I got while importing into an empty instance.
Most of the optionSets are in the package, but these are not. YOu can get the package by clicking on the three dots of the module and clicking on "download package.."

Oj5hUu2m0gP	Program		Invalid reference [jcdO38xlH2P] (ProgramSection) on object ENTO- Mosquito [Oj5hUu2m0gP] (Program) for association `programSections`.
Mk9ocCvATwK	Program		Invalid reference [MHwU8yVTvfz] (ProgramSection) on object ENTO- Mosquito collection [Mk9ocCvATwK] (Program) for association `programSections`.
kjoryVqylRY	TrackedEntityAttribute		Invalid reference [aqXwFBAKypx] (OptionSet) on object Gonotrophic status [kjoryVqylRY] (TrackedEntityAttribute) for association `optionSet`.
XQ1WcRJageG	TrackedEntityAttribute		Invalid reference [HtC7IunhCat] (OptionSet) on object Sex [XQ1WcRJageG] (TrackedEntityAttribute) for association `optionSet`.
fcSVYjWZrY4	TrackedEntityAttribute		Invalid reference [u4xoL9tKMiC] (OptionSet) on object Bednet present [fcSVYjWZrY4] (TrackedEntityAttribute) for association `optionSet`.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1602589281521645123.png )

**Comment by adrianq** [comment]
It seems to be fixed in 2.14.0
