### ISSUE TITLE
[User feedback] Add functionality to include indicators in pogram packages

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/metadata-synchronization-blessed#92]
## dhis2

Username: fernandezl

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
- Platform: Win32

## User report
URL: http://localhost:8080/api/apps/MetaData-Synchronization/index.html#/modules/edit/NHk6vwzHfz9

For now, we cannot include  indicators when we create a package composed of programs

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1604580709131258409.png )

**Comment by adrianq** [comment]
Program indicators can be included in a "program module" (version 2.14.0)
